baseURL = 'https://noegel.io/'
languageCode = "en"
defaultContentLanguage = "en"
languageName = "English"
title = 'noegel.io'
theme = 'loveit'


[params]
title = "Daniel Nögel"

[params.page]
lightgallery = true
description = ""
css = ["style.css"]


[menu]
    [[menu.main]]
    weight = 1
    identifier = "posts"
    post = ""
    name = "Posts"
    url = "/posts/"
    [[menu.main]]
    weight = 2
    identifier = "about"
    post = ""
    name = "About"
    url = "/about/"
    [[menu.main]]
    weight = 3
    identifier = "projects"
    post = ""
    name = "Time capsule"
    url = "/projects/"

[old]
    [[oldmenu.main]]
    weight = 3
    identifier = "read"
    post = ""
    name = "Reading"
    url = "/read/"

[outputs]
  home = ["HTML", "RSS", "JSON"]


[markup]
  [markup.goldmark]
    [markup.goldmark.renderer]
      unsafe = true




[params.author]
name = "Daniel Nögel"
link = "/"

[params.social]
GitHub = "dnoegel"
Linkedin = "daniel-n%C3%B6gel-b14a5bb2/"
Twitter = "danielnoegel"



[params.header]
[params.header.title]
  logo = ""
  name = "noegel.io"
  # you can add extra information before the name (HTML format is supported), such as icons
  _pre = "<img style='height:32px;margin-right:10px;border-radius:32px;vertical-align:middle' src='/images/dn.png'"
  pre = ""
  # you can add extra information after the name (HTML format is supported), such as icons
  post = ""
  # whether to use typeit a nimation for title name
  typeit = false

[params.search]
    enable = true
    type = "lunr"
    contentLength = 4000
    placeholder = ""
    maxResultLength = 10
    snippetLength = 60
    highlightTag = "em"
    absoluteURL = false

[params.app]
title = "Daniel Nögel"

[params.home]
[params.home.profile]
  enable = true
  avatarURL = "/images/dn.png"
  title = ""
  subtitle = "Things I learned"
  typeit = false
  social = true
